packages:
  - apps/*
  - packages/*

catalog:
  convex: ^1.42.1
  dotenv: ^17.4.2
  typescript: 6.0.3
  zod: ^4.4.3

overrides:
  use-sync-external-store: ^1.4.0
  lightningcss: 1.30.1

allowBuilds:
  "@clerk/shared": true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - '@clerk/clerk-js@6.29.2'
  - '@clerk/expo@4.5.0'
  - '@clerk/react@6.14.4'
  - '@clerk/shared@4.29.2'
