/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as QrOperadorRouteImport } from './routes/qr-operador'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EngenhariaRouteRouteImport } from './routes/engenharia/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as EngenhariaIndexRouteImport } from './routes/engenharia/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as QTokenRouteImport } from './routes/q/$token'
import { Route as PortalProjectIdRouteImport } from './routes/portal/$projectId'
import { Route as EngenhariaUsuariosRouteImport } from './routes/engenharia/usuarios'
import { Route as EngenhariaRegistroDeCampoRouteImport } from './routes/engenharia/registro-de-campo'
import { Route as EngenhariaQrCodesRouteImport } from './routes/engenharia/qr-codes'
import { Route as EngenhariaRelatoriosRouteRouteImport } from './routes/engenharia/relatorios/route'
import { Route as EngenhariaRelatoriosIndexRouteImport } from './routes/engenharia/relatorios/index'
import { Route as EngenhariaRelatoriosProjectIdRouteImport } from './routes/engenharia/relatorios/$projectId'
import { Route as EngenhariaQrTokenRouteImport } from './routes/engenharia/qr/$token'
import { Route as EngenhariaEquipamentoIdRouteImport } from './routes/engenharia/equipamento/$id'
import { Route as EngenhariaRelatoriosProjectIdTorresRouteImport } from './routes/engenharia/relatorios/$projectId.torres'
import { Route as EngenhariaRelatoriosProjectIdImprimirRouteImport } from './routes/engenharia/relatorios/$projectId.imprimir'
import { Route as EngenhariaRelatoriosProjectIdGlobalRouteImport } from './routes/engenharia/relatorios/$projectId.global'
import { Route as EngenhariaRelatoriosProjectIdEntregasRouteImport } from './routes/engenharia/relatorios/$projectId.entregas'
import { Route as EngenhariaRelatoriosProjectIdEditarRouteImport } from './routes/engenharia/relatorios/$projectId.editar'
import { Route as EngenhariaRelatoriosProjectIdDashboardRouteImport } from './routes/engenharia/relatorios/$projectId.dashboard'
import { Route as EngenhariaRelatoriosProjectIdAssistenteRouteImport } from './routes/engenharia/relatorios/$projectId.assistente'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const QrOperadorRoute = QrOperadorRouteImport.update({
  id: '/qr-operador',
  path: '/qr-operador',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaRouteRoute = EngenhariaRouteRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaIndexRoute = EngenhariaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngenhariaRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProjectIdRoute = PortalProjectIdRouteImport.update({
  id: '/portal/$projectId',
  path: '/portal/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaUsuariosRoute = EngenhariaUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => EngenhariaRouteRoute,
} as any)
const EngenhariaRegistroDeCampoRoute =
  EngenhariaRegistroDeCampoRouteImport.update({
    id: '/registro-de-campo',
    path: '/registro-de-campo',
    getParentRoute: () => EngenhariaRouteRoute,
  } as any)
const EngenhariaQrCodesRoute = EngenhariaQrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => EngenhariaRouteRoute,
} as any)
const EngenhariaRelatoriosRouteRoute =
  EngenhariaRelatoriosRouteRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => EngenhariaRouteRoute,
  } as any)
const EngenhariaRelatoriosIndexRoute =
  EngenhariaRelatoriosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EngenhariaRelatoriosRouteRoute,
  } as any)
const EngenhariaRelatoriosProjectIdRoute =
  EngenhariaRelatoriosProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => EngenhariaRelatoriosRouteRoute,
  } as any)
const EngenhariaQrTokenRoute = EngenhariaQrTokenRouteImport.update({
  id: '/qr/$token',
  path: '/qr/$token',
  getParentRoute: () => EngenhariaRouteRoute,
} as any)
const EngenhariaEquipamentoIdRoute = EngenhariaEquipamentoIdRouteImport.update({
  id: '/equipamento/$id',
  path: '/equipamento/$id',
  getParentRoute: () => EngenhariaRouteRoute,
} as any)
const EngenhariaRelatoriosProjectIdTorresRoute =
  EngenhariaRelatoriosProjectIdTorresRouteImport.update({
    id: '/torres',
    path: '/torres',
    getParentRoute: () => EngenhariaRelatoriosProjectIdRoute,
  } as any)
const EngenhariaRelatoriosProjectIdImprimirRoute =
  EngenhariaRelatoriosProjectIdImprimirRouteImport.update({
    id: '/imprimir',
    path: '/imprimir',
    getParentRoute: () => EngenhariaRelatoriosProjectIdRoute,
  } as any)
const EngenhariaRelatoriosProjectIdGlobalRoute =
  EngenhariaRelatoriosProjectIdGlobalRouteImport.update({
    id: '/global',
    path: '/global',
    getParentRoute: () => EngenhariaRelatoriosProjectIdRoute,
  } as any)
const EngenhariaRelatoriosProjectIdEntregasRoute =
  EngenhariaRelatoriosProjectIdEntregasRouteImport.update({
    id: '/entregas',
    path: '/entregas',
    getParentRoute: () => EngenhariaRelatoriosProjectIdRoute,
  } as any)
const EngenhariaRelatoriosProjectIdEditarRoute =
  EngenhariaRelatoriosProjectIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => EngenhariaRelatoriosProjectIdRoute,
  } as any)
const EngenhariaRelatoriosProjectIdDashboardRoute =
  EngenhariaRelatoriosProjectIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => EngenhariaRelatoriosProjectIdRoute,
  } as any)
const EngenhariaRelatoriosProjectIdAssistenteRoute =
  EngenhariaRelatoriosProjectIdAssistenteRouteImport.update({
    id: '/assistente',
    path: '/assistente',
    getParentRoute: () => EngenhariaRelatoriosProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/engenharia': typeof EngenhariaRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/qr-operador': typeof QrOperadorRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/engenharia/relatorios': typeof EngenhariaRelatoriosRouteRouteWithChildren
  '/engenharia/qr-codes': typeof EngenhariaQrCodesRoute
  '/engenharia/registro-de-campo': typeof EngenhariaRegistroDeCampoRoute
  '/engenharia/usuarios': typeof EngenhariaUsuariosRoute
  '/portal/$projectId': typeof PortalProjectIdRoute
  '/q/$token': typeof QTokenRoute
  '/app/': typeof AppIndexRoute
  '/engenharia/': typeof EngenhariaIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/engenharia/equipamento/$id': typeof EngenhariaEquipamentoIdRoute
  '/engenharia/qr/$token': typeof EngenhariaQrTokenRoute
  '/engenharia/relatorios/$projectId': typeof EngenhariaRelatoriosProjectIdRouteWithChildren
  '/engenharia/relatorios/': typeof EngenhariaRelatoriosIndexRoute
  '/engenharia/relatorios/$projectId/assistente': typeof EngenhariaRelatoriosProjectIdAssistenteRoute
  '/engenharia/relatorios/$projectId/dashboard': typeof EngenhariaRelatoriosProjectIdDashboardRoute
  '/engenharia/relatorios/$projectId/editar': typeof EngenhariaRelatoriosProjectIdEditarRoute
  '/engenharia/relatorios/$projectId/entregas': typeof EngenhariaRelatoriosProjectIdEntregasRoute
  '/engenharia/relatorios/$projectId/global': typeof EngenhariaRelatoriosProjectIdGlobalRoute
  '/engenharia/relatorios/$projectId/imprimir': typeof EngenhariaRelatoriosProjectIdImprimirRoute
  '/engenharia/relatorios/$projectId/torres': typeof EngenhariaRelatoriosProjectIdTorresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qr-operador': typeof QrOperadorRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/engenharia/qr-codes': typeof EngenhariaQrCodesRoute
  '/engenharia/registro-de-campo': typeof EngenhariaRegistroDeCampoRoute
  '/engenharia/usuarios': typeof EngenhariaUsuariosRoute
  '/portal/$projectId': typeof PortalProjectIdRoute
  '/q/$token': typeof QTokenRoute
  '/app': typeof AppIndexRoute
  '/engenharia': typeof EngenhariaIndexRoute
  '/portal': typeof PortalIndexRoute
  '/engenharia/equipamento/$id': typeof EngenhariaEquipamentoIdRoute
  '/engenharia/qr/$token': typeof EngenhariaQrTokenRoute
  '/engenharia/relatorios/$projectId': typeof EngenhariaRelatoriosProjectIdRouteWithChildren
  '/engenharia/relatorios': typeof EngenhariaRelatoriosIndexRoute
  '/engenharia/relatorios/$projectId/assistente': typeof EngenhariaRelatoriosProjectIdAssistenteRoute
  '/engenharia/relatorios/$projectId/dashboard': typeof EngenhariaRelatoriosProjectIdDashboardRoute
  '/engenharia/relatorios/$projectId/editar': typeof EngenhariaRelatoriosProjectIdEditarRoute
  '/engenharia/relatorios/$projectId/entregas': typeof EngenhariaRelatoriosProjectIdEntregasRoute
  '/engenharia/relatorios/$projectId/global': typeof EngenhariaRelatoriosProjectIdGlobalRoute
  '/engenharia/relatorios/$projectId/imprimir': typeof EngenhariaRelatoriosProjectIdImprimirRoute
  '/engenharia/relatorios/$projectId/torres': typeof EngenhariaRelatoriosProjectIdTorresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/engenharia': typeof EngenhariaRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/qr-operador': typeof QrOperadorRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/engenharia/relatorios': typeof EngenhariaRelatoriosRouteRouteWithChildren
  '/engenharia/qr-codes': typeof EngenhariaQrCodesRoute
  '/engenharia/registro-de-campo': typeof EngenhariaRegistroDeCampoRoute
  '/engenharia/usuarios': typeof EngenhariaUsuariosRoute
  '/portal/$projectId': typeof PortalProjectIdRoute
  '/q/$token': typeof QTokenRoute
  '/app/': typeof AppIndexRoute
  '/engenharia/': typeof EngenhariaIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/engenharia/equipamento/$id': typeof EngenhariaEquipamentoIdRoute
  '/engenharia/qr/$token': typeof EngenhariaQrTokenRoute
  '/engenharia/relatorios/$projectId': typeof EngenhariaRelatoriosProjectIdRouteWithChildren
  '/engenharia/relatorios/': typeof EngenhariaRelatoriosIndexRoute
  '/engenharia/relatorios/$projectId/assistente': typeof EngenhariaRelatoriosProjectIdAssistenteRoute
  '/engenharia/relatorios/$projectId/dashboard': typeof EngenhariaRelatoriosProjectIdDashboardRoute
  '/engenharia/relatorios/$projectId/editar': typeof EngenhariaRelatoriosProjectIdEditarRoute
  '/engenharia/relatorios/$projectId/entregas': typeof EngenhariaRelatoriosProjectIdEntregasRoute
  '/engenharia/relatorios/$projectId/global': typeof EngenhariaRelatoriosProjectIdGlobalRoute
  '/engenharia/relatorios/$projectId/imprimir': typeof EngenhariaRelatoriosProjectIdImprimirRoute
  '/engenharia/relatorios/$projectId/torres': typeof EngenhariaRelatoriosProjectIdTorresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/engenharia'
    | '/login'
    | '/qr-operador'
    | '/sign-in'
    | '/sign-up'
    | '/engenharia/relatorios'
    | '/engenharia/qr-codes'
    | '/engenharia/registro-de-campo'
    | '/engenharia/usuarios'
    | '/portal/$projectId'
    | '/q/$token'
    | '/app/'
    | '/engenharia/'
    | '/portal/'
    | '/engenharia/equipamento/$id'
    | '/engenharia/qr/$token'
    | '/engenharia/relatorios/$projectId'
    | '/engenharia/relatorios/'
    | '/engenharia/relatorios/$projectId/assistente'
    | '/engenharia/relatorios/$projectId/dashboard'
    | '/engenharia/relatorios/$projectId/editar'
    | '/engenharia/relatorios/$projectId/entregas'
    | '/engenharia/relatorios/$projectId/global'
    | '/engenharia/relatorios/$projectId/imprimir'
    | '/engenharia/relatorios/$projectId/torres'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/qr-operador'
    | '/sign-in'
    | '/sign-up'
    | '/engenharia/qr-codes'
    | '/engenharia/registro-de-campo'
    | '/engenharia/usuarios'
    | '/portal/$projectId'
    | '/q/$token'
    | '/app'
    | '/engenharia'
    | '/portal'
    | '/engenharia/equipamento/$id'
    | '/engenharia/qr/$token'
    | '/engenharia/relatorios/$projectId'
    | '/engenharia/relatorios'
    | '/engenharia/relatorios/$projectId/assistente'
    | '/engenharia/relatorios/$projectId/dashboard'
    | '/engenharia/relatorios/$projectId/editar'
    | '/engenharia/relatorios/$projectId/entregas'
    | '/engenharia/relatorios/$projectId/global'
    | '/engenharia/relatorios/$projectId/imprimir'
    | '/engenharia/relatorios/$projectId/torres'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/engenharia'
    | '/login'
    | '/qr-operador'
    | '/sign-in'
    | '/sign-up'
    | '/engenharia/relatorios'
    | '/engenharia/qr-codes'
    | '/engenharia/registro-de-campo'
    | '/engenharia/usuarios'
    | '/portal/$projectId'
    | '/q/$token'
    | '/app/'
    | '/engenharia/'
    | '/portal/'
    | '/engenharia/equipamento/$id'
    | '/engenharia/qr/$token'
    | '/engenharia/relatorios/$projectId'
    | '/engenharia/relatorios/'
    | '/engenharia/relatorios/$projectId/assistente'
    | '/engenharia/relatorios/$projectId/dashboard'
    | '/engenharia/relatorios/$projectId/editar'
    | '/engenharia/relatorios/$projectId/entregas'
    | '/engenharia/relatorios/$projectId/global'
    | '/engenharia/relatorios/$projectId/imprimir'
    | '/engenharia/relatorios/$projectId/torres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  EngenhariaRouteRoute: typeof EngenhariaRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  QrOperadorRoute: typeof QrOperadorRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  PortalProjectIdRoute: typeof PortalProjectIdRoute
  QTokenRoute: typeof QTokenRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-operador': {
      id: '/qr-operador'
      path: '/qr-operador'
      fullPath: '/qr-operador'
      preLoaderRoute: typeof QrOperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia': {
      id: '/engenharia'
      path: '/engenharia'
      fullPath: '/engenharia'
      preLoaderRoute: typeof EngenhariaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia/': {
      id: '/engenharia/'
      path: '/'
      fullPath: '/engenharia/'
      preLoaderRoute: typeof EngenhariaIndexRouteImport
      parentRoute: typeof EngenhariaRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$projectId': {
      id: '/portal/$projectId'
      path: '/portal/$projectId'
      fullPath: '/portal/$projectId'
      preLoaderRoute: typeof PortalProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia/usuarios': {
      id: '/engenharia/usuarios'
      path: '/usuarios'
      fullPath: '/engenharia/usuarios'
      preLoaderRoute: typeof EngenhariaUsuariosRouteImport
      parentRoute: typeof EngenhariaRouteRoute
    }
    '/engenharia/registro-de-campo': {
      id: '/engenharia/registro-de-campo'
      path: '/registro-de-campo'
      fullPath: '/engenharia/registro-de-campo'
      preLoaderRoute: typeof EngenhariaRegistroDeCampoRouteImport
      parentRoute: typeof EngenhariaRouteRoute
    }
    '/engenharia/qr-codes': {
      id: '/engenharia/qr-codes'
      path: '/qr-codes'
      fullPath: '/engenharia/qr-codes'
      preLoaderRoute: typeof EngenhariaQrCodesRouteImport
      parentRoute: typeof EngenhariaRouteRoute
    }
    '/engenharia/relatorios': {
      id: '/engenharia/relatorios'
      path: '/relatorios'
      fullPath: '/engenharia/relatorios'
      preLoaderRoute: typeof EngenhariaRelatoriosRouteRouteImport
      parentRoute: typeof EngenhariaRouteRoute
    }
    '/engenharia/relatorios/': {
      id: '/engenharia/relatorios/'
      path: '/'
      fullPath: '/engenharia/relatorios/'
      preLoaderRoute: typeof EngenhariaRelatoriosIndexRouteImport
      parentRoute: typeof EngenhariaRelatoriosRouteRoute
    }
    '/engenharia/relatorios/$projectId': {
      id: '/engenharia/relatorios/$projectId'
      path: '/$projectId'
      fullPath: '/engenharia/relatorios/$projectId'
      preLoaderRoute: typeof EngenhariaRelatoriosProjectIdRouteImport
      parentRoute: typeof EngenhariaRelatoriosRouteRoute
    }
    '/engenharia/qr/$token': {
      id: '/engenharia/qr/$token'
      path: '/qr/$token'
      fullPath: '/engenharia/qr/$token'
      preLoaderRoute: typeof EngenhariaQrTokenRouteImport
      parentRoute: typeof EngenhariaRouteRoute
    }
    '/engenharia/equipamento/$id': {
      id: '/engenharia/equipamento/$id'
      path: '/equipamento/$id'
      fullPath: '/engenharia/equipamento/$id'
      preLoaderRoute: typeof EngenhariaEquipamentoIdRouteImport
      parentRoute: typeof EngenhariaRouteRoute
    }
    '/engenharia/relatorios/$projectId/torres': {
      id: '/engenharia/relatorios/$projectId/torres'
      path: '/torres'
      fullPath: '/engenharia/relatorios/$projectId/torres'
      preLoaderRoute: typeof EngenhariaRelatoriosProjectIdTorresRouteImport
      parentRoute: typeof EngenhariaRelatoriosProjectIdRoute
    }
    '/engenharia/relatorios/$projectId/imprimir': {
      id: '/engenharia/relatorios/$projectId/imprimir'
      path: '/imprimir'
      fullPath: '/engenharia/relatorios/$projectId/imprimir'
      preLoaderRoute: typeof EngenhariaRelatoriosProjectIdImprimirRouteImport
      parentRoute: typeof EngenhariaRelatoriosProjectIdRoute
    }
    '/engenharia/relatorios/$projectId/global': {
      id: '/engenharia/relatorios/$projectId/global'
      path: '/global'
      fullPath: '/engenharia/relatorios/$projectId/global'
      preLoaderRoute: typeof EngenhariaRelatoriosProjectIdGlobalRouteImport
      parentRoute: typeof EngenhariaRelatoriosProjectIdRoute
    }
    '/engenharia/relatorios/$projectId/entregas': {
      id: '/engenharia/relatorios/$projectId/entregas'
      path: '/entregas'
      fullPath: '/engenharia/relatorios/$projectId/entregas'
      preLoaderRoute: typeof EngenhariaRelatoriosProjectIdEntregasRouteImport
      parentRoute: typeof EngenhariaRelatoriosProjectIdRoute
    }
    '/engenharia/relatorios/$projectId/editar': {
      id: '/engenharia/relatorios/$projectId/editar'
      path: '/editar'
      fullPath: '/engenharia/relatorios/$projectId/editar'
      preLoaderRoute: typeof EngenhariaRelatoriosProjectIdEditarRouteImport
      parentRoute: typeof EngenhariaRelatoriosProjectIdRoute
    }
    '/engenharia/relatorios/$projectId/dashboard': {
      id: '/engenharia/relatorios/$projectId/dashboard'
      path: '/dashboard'
      fullPath: '/engenharia/relatorios/$projectId/dashboard'
      preLoaderRoute: typeof EngenhariaRelatoriosProjectIdDashboardRouteImport
      parentRoute: typeof EngenhariaRelatoriosProjectIdRoute
    }
    '/engenharia/relatorios/$projectId/assistente': {
      id: '/engenharia/relatorios/$projectId/assistente'
      path: '/assistente'
      fullPath: '/engenharia/relatorios/$projectId/assistente'
      preLoaderRoute: typeof EngenhariaRelatoriosProjectIdAssistenteRouteImport
      parentRoute: typeof EngenhariaRelatoriosProjectIdRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface EngenhariaRelatoriosProjectIdRouteChildren {
  EngenhariaRelatoriosProjectIdAssistenteRoute: typeof EngenhariaRelatoriosProjectIdAssistenteRoute
  EngenhariaRelatoriosProjectIdDashboardRoute: typeof EngenhariaRelatoriosProjectIdDashboardRoute
  EngenhariaRelatoriosProjectIdEditarRoute: typeof EngenhariaRelatoriosProjectIdEditarRoute
  EngenhariaRelatoriosProjectIdEntregasRoute: typeof EngenhariaRelatoriosProjectIdEntregasRoute
  EngenhariaRelatoriosProjectIdGlobalRoute: typeof EngenhariaRelatoriosProjectIdGlobalRoute
  EngenhariaRelatoriosProjectIdImprimirRoute: typeof EngenhariaRelatoriosProjectIdImprimirRoute
  EngenhariaRelatoriosProjectIdTorresRoute: typeof EngenhariaRelatoriosProjectIdTorresRoute
}

const EngenhariaRelatoriosProjectIdRouteChildren: EngenhariaRelatoriosProjectIdRouteChildren =
  {
    EngenhariaRelatoriosProjectIdAssistenteRoute:
      EngenhariaRelatoriosProjectIdAssistenteRoute,
    EngenhariaRelatoriosProjectIdDashboardRoute:
      EngenhariaRelatoriosProjectIdDashboardRoute,
    EngenhariaRelatoriosProjectIdEditarRoute:
      EngenhariaRelatoriosProjectIdEditarRoute,
    EngenhariaRelatoriosProjectIdEntregasRoute:
      EngenhariaRelatoriosProjectIdEntregasRoute,
    EngenhariaRelatoriosProjectIdGlobalRoute:
      EngenhariaRelatoriosProjectIdGlobalRoute,
    EngenhariaRelatoriosProjectIdImprimirRoute:
      EngenhariaRelatoriosProjectIdImprimirRoute,
    EngenhariaRelatoriosProjectIdTorresRoute:
      EngenhariaRelatoriosProjectIdTorresRoute,
  }

const EngenhariaRelatoriosProjectIdRouteWithChildren =
  EngenhariaRelatoriosProjectIdRoute._addFileChildren(
    EngenhariaRelatoriosProjectIdRouteChildren,
  )

interface EngenhariaRelatoriosRouteRouteChildren {
  EngenhariaRelatoriosProjectIdRoute: typeof EngenhariaRelatoriosProjectIdRouteWithChildren
  EngenhariaRelatoriosIndexRoute: typeof EngenhariaRelatoriosIndexRoute
}

const EngenhariaRelatoriosRouteRouteChildren: EngenhariaRelatoriosRouteRouteChildren =
  {
    EngenhariaRelatoriosProjectIdRoute:
      EngenhariaRelatoriosProjectIdRouteWithChildren,
    EngenhariaRelatoriosIndexRoute: EngenhariaRelatoriosIndexRoute,
  }

const EngenhariaRelatoriosRouteRouteWithChildren =
  EngenhariaRelatoriosRouteRoute._addFileChildren(
    EngenhariaRelatoriosRouteRouteChildren,
  )

interface EngenhariaRouteRouteChildren {
  EngenhariaRelatoriosRouteRoute: typeof EngenhariaRelatoriosRouteRouteWithChildren
  EngenhariaQrCodesRoute: typeof EngenhariaQrCodesRoute
  EngenhariaRegistroDeCampoRoute: typeof EngenhariaRegistroDeCampoRoute
  EngenhariaUsuariosRoute: typeof EngenhariaUsuariosRoute
  EngenhariaIndexRoute: typeof EngenhariaIndexRoute
  EngenhariaEquipamentoIdRoute: typeof EngenhariaEquipamentoIdRoute
  EngenhariaQrTokenRoute: typeof EngenhariaQrTokenRoute
}

const EngenhariaRouteRouteChildren: EngenhariaRouteRouteChildren = {
  EngenhariaRelatoriosRouteRoute: EngenhariaRelatoriosRouteRouteWithChildren,
  EngenhariaQrCodesRoute: EngenhariaQrCodesRoute,
  EngenhariaRegistroDeCampoRoute: EngenhariaRegistroDeCampoRoute,
  EngenhariaUsuariosRoute: EngenhariaUsuariosRoute,
  EngenhariaIndexRoute: EngenhariaIndexRoute,
  EngenhariaEquipamentoIdRoute: EngenhariaEquipamentoIdRoute,
  EngenhariaQrTokenRoute: EngenhariaQrTokenRoute,
}

const EngenhariaRouteRouteWithChildren = EngenhariaRouteRoute._addFileChildren(
  EngenhariaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  EngenhariaRouteRoute: EngenhariaRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  QrOperadorRoute: QrOperadorRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  PortalProjectIdRoute: PortalProjectIdRoute,
  QTokenRoute: QTokenRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
