/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WebsiteRouteImport } from './routes/_website'
import { Route as RhRouteRouteImport } from './routes/rh/route'
import { Route as FinanceiroRouteRouteImport } from './routes/financeiro/route'
import { Route as EstoqueRouteRouteImport } from './routes/estoque/route'
import { Route as EngenhariaRouteRouteImport } from './routes/engenharia/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as RhIndexRouteImport } from './routes/rh/index'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro/index'
import { Route as EstoqueIndexRouteImport } from './routes/estoque/index'
import { Route as EngenhariaIndexRouteImport } from './routes/engenharia/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as WebsiteIndexRouteImport } from './routes/_website/index'
import { Route as FinanceiroRelatoriosRouteImport } from './routes/financeiro/relatorios'
import { Route as FinanceiroContasReceberRouteImport } from './routes/financeiro/contas-receber'
import { Route as FinanceiroContasPagarRouteImport } from './routes/financeiro/contas-pagar'
import { Route as FinanceiroContasBancariasRouteImport } from './routes/financeiro/contas-bancarias'
import { Route as FinanceiroConciliacaoRouteImport } from './routes/financeiro/conciliacao'
import { Route as FinanceiroClientesRouteImport } from './routes/financeiro/clientes'
import { Route as FinanceiroCategoriasRouteImport } from './routes/financeiro/categorias'
import { Route as EstoqueSitesRouteImport } from './routes/estoque/sites'
import { Route as EstoqueSaidaRouteImport } from './routes/estoque/saida'
import { Route as EstoqueProdutosRouteImport } from './routes/estoque/produtos'
import { Route as EstoqueMovimentacoesRouteImport } from './routes/estoque/movimentacoes'
import { Route as EstoqueFornecedoresRouteImport } from './routes/estoque/fornecedores'
import { Route as EstoqueEntradaRouteImport } from './routes/estoque/entrada'
import { Route as EstoqueAjustesRouteImport } from './routes/estoque/ajustes'
import { Route as WebsiteSobreRouteImport } from './routes/_website/sobre'
import { Route as WebsiteServicosRouteImport } from './routes/_website/servicos'
import { Route as WebsitePoliticaPrivacidadeRouteImport } from './routes/_website/politica-privacidade'
import { Route as WebsiteManutencaoRouteImport } from './routes/_website/manutencao'
import { Route as WebsiteCarreirasRouteImport } from './routes/_website/carreiras'
import { Route as WebsiteProjetosIndexRouteImport } from './routes/_website/projetos/index'
import { Route as WebsiteProjetosIdRouteImport } from './routes/_website/projetos/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteRoute = WebsiteRouteImport.update({
  id: '/_website',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRouteRoute = RhRouteRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRouteRoute = FinanceiroRouteRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRouteRoute = EstoqueRouteRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaRouteRoute = EngenhariaRouteRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const RhIndexRoute = RhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RhRouteRoute,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRouteRoute,
} as any)
const EstoqueIndexRoute = EstoqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstoqueRouteRoute,
} as any)
const EngenhariaIndexRoute = EngenhariaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngenhariaRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRoute,
} as any)
const FinanceiroRelatoriosRoute = FinanceiroRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => FinanceiroRouteRoute,
} as any)
const FinanceiroContasReceberRoute = FinanceiroContasReceberRouteImport.update({
  id: '/contas-receber',
  path: '/contas-receber',
  getParentRoute: () => FinanceiroRouteRoute,
} as any)
const FinanceiroContasPagarRoute = FinanceiroContasPagarRouteImport.update({
  id: '/contas-pagar',
  path: '/contas-pagar',
  getParentRoute: () => FinanceiroRouteRoute,
} as any)
const FinanceiroContasBancariasRoute =
  FinanceiroContasBancariasRouteImport.update({
    id: '/contas-bancarias',
    path: '/contas-bancarias',
    getParentRoute: () => FinanceiroRouteRoute,
  } as any)
const FinanceiroConciliacaoRoute = FinanceiroConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => FinanceiroRouteRoute,
} as any)
const FinanceiroClientesRoute = FinanceiroClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => FinanceiroRouteRoute,
} as any)
const FinanceiroCategoriasRoute = FinanceiroCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => FinanceiroRouteRoute,
} as any)
const EstoqueSitesRoute = EstoqueSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => EstoqueRouteRoute,
} as any)
const EstoqueSaidaRoute = EstoqueSaidaRouteImport.update({
  id: '/saida',
  path: '/saida',
  getParentRoute: () => EstoqueRouteRoute,
} as any)
const EstoqueProdutosRoute = EstoqueProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => EstoqueRouteRoute,
} as any)
const EstoqueMovimentacoesRoute = EstoqueMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => EstoqueRouteRoute,
} as any)
const EstoqueFornecedoresRoute = EstoqueFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => EstoqueRouteRoute,
} as any)
const EstoqueEntradaRoute = EstoqueEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => EstoqueRouteRoute,
} as any)
const EstoqueAjustesRoute = EstoqueAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => EstoqueRouteRoute,
} as any)
const WebsiteSobreRoute = WebsiteSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteServicosRoute = WebsiteServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsitePoliticaPrivacidadeRoute =
  WebsitePoliticaPrivacidadeRouteImport.update({
    id: '/politica-privacidade',
    path: '/politica-privacidade',
    getParentRoute: () => WebsiteRoute,
  } as any)
const WebsiteManutencaoRoute = WebsiteManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteCarreirasRoute = WebsiteCarreirasRouteImport.update({
  id: '/carreiras',
  path: '/carreiras',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteProjetosIndexRoute = WebsiteProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => WebsiteRoute,
} as any)
const WebsiteProjetosIdRoute = WebsiteProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => WebsiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/engenharia': typeof EngenhariaRouteRouteWithChildren
  '/estoque': typeof EstoqueRouteRouteWithChildren
  '/financeiro': typeof FinanceiroRouteRouteWithChildren
  '/rh': typeof RhRouteRouteWithChildren
  '/': typeof WebsiteIndexRoute
  '/login': typeof LoginRoute
  '/carreiras': typeof WebsiteCarreirasRoute
  '/manutencao': typeof WebsiteManutencaoRoute
  '/politica-privacidade': typeof WebsitePoliticaPrivacidadeRoute
  '/servicos': typeof WebsiteServicosRoute
  '/sobre': typeof WebsiteSobreRoute
  '/estoque/ajustes': typeof EstoqueAjustesRoute
  '/estoque/entrada': typeof EstoqueEntradaRoute
  '/estoque/fornecedores': typeof EstoqueFornecedoresRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/produtos': typeof EstoqueProdutosRoute
  '/estoque/saida': typeof EstoqueSaidaRoute
  '/estoque/sites': typeof EstoqueSitesRoute
  '/financeiro/categorias': typeof FinanceiroCategoriasRoute
  '/financeiro/clientes': typeof FinanceiroClientesRoute
  '/financeiro/conciliacao': typeof FinanceiroConciliacaoRoute
  '/financeiro/contas-bancarias': typeof FinanceiroContasBancariasRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/relatorios': typeof FinanceiroRelatoriosRoute
  '/app/': typeof AppIndexRoute
  '/engenharia/': typeof EngenhariaIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/rh/': typeof RhIndexRoute
  '/projetos/$id': typeof WebsiteProjetosIdRoute
  '/projetos/': typeof WebsiteProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/carreiras': typeof WebsiteCarreirasRoute
  '/manutencao': typeof WebsiteManutencaoRoute
  '/politica-privacidade': typeof WebsitePoliticaPrivacidadeRoute
  '/servicos': typeof WebsiteServicosRoute
  '/sobre': typeof WebsiteSobreRoute
  '/estoque/ajustes': typeof EstoqueAjustesRoute
  '/estoque/entrada': typeof EstoqueEntradaRoute
  '/estoque/fornecedores': typeof EstoqueFornecedoresRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/produtos': typeof EstoqueProdutosRoute
  '/estoque/saida': typeof EstoqueSaidaRoute
  '/estoque/sites': typeof EstoqueSitesRoute
  '/financeiro/categorias': typeof FinanceiroCategoriasRoute
  '/financeiro/clientes': typeof FinanceiroClientesRoute
  '/financeiro/conciliacao': typeof FinanceiroConciliacaoRoute
  '/financeiro/contas-bancarias': typeof FinanceiroContasBancariasRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/relatorios': typeof FinanceiroRelatoriosRoute
  '/': typeof WebsiteIndexRoute
  '/app': typeof AppIndexRoute
  '/engenharia': typeof EngenhariaIndexRoute
  '/estoque': typeof EstoqueIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/rh': typeof RhIndexRoute
  '/projetos/$id': typeof WebsiteProjetosIdRoute
  '/projetos': typeof WebsiteProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/engenharia': typeof EngenhariaRouteRouteWithChildren
  '/estoque': typeof EstoqueRouteRouteWithChildren
  '/financeiro': typeof FinanceiroRouteRouteWithChildren
  '/rh': typeof RhRouteRouteWithChildren
  '/_website': typeof WebsiteRouteWithChildren
  '/login': typeof LoginRoute
  '/_website/carreiras': typeof WebsiteCarreirasRoute
  '/_website/manutencao': typeof WebsiteManutencaoRoute
  '/_website/politica-privacidade': typeof WebsitePoliticaPrivacidadeRoute
  '/_website/servicos': typeof WebsiteServicosRoute
  '/_website/sobre': typeof WebsiteSobreRoute
  '/estoque/ajustes': typeof EstoqueAjustesRoute
  '/estoque/entrada': typeof EstoqueEntradaRoute
  '/estoque/fornecedores': typeof EstoqueFornecedoresRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/produtos': typeof EstoqueProdutosRoute
  '/estoque/saida': typeof EstoqueSaidaRoute
  '/estoque/sites': typeof EstoqueSitesRoute
  '/financeiro/categorias': typeof FinanceiroCategoriasRoute
  '/financeiro/clientes': typeof FinanceiroClientesRoute
  '/financeiro/conciliacao': typeof FinanceiroConciliacaoRoute
  '/financeiro/contas-bancarias': typeof FinanceiroContasBancariasRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/relatorios': typeof FinanceiroRelatoriosRoute
  '/_website/': typeof WebsiteIndexRoute
  '/app/': typeof AppIndexRoute
  '/engenharia/': typeof EngenhariaIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/rh/': typeof RhIndexRoute
  '/_website/projetos/$id': typeof WebsiteProjetosIdRoute
  '/_website/projetos/': typeof WebsiteProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/engenharia'
    | '/estoque'
    | '/financeiro'
    | '/rh'
    | '/'
    | '/login'
    | '/carreiras'
    | '/manutencao'
    | '/politica-privacidade'
    | '/servicos'
    | '/sobre'
    | '/estoque/ajustes'
    | '/estoque/entrada'
    | '/estoque/fornecedores'
    | '/estoque/movimentacoes'
    | '/estoque/produtos'
    | '/estoque/saida'
    | '/estoque/sites'
    | '/financeiro/categorias'
    | '/financeiro/clientes'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-bancarias'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/relatorios'
    | '/app/'
    | '/engenharia/'
    | '/estoque/'
    | '/financeiro/'
    | '/rh/'
    | '/projetos/$id'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/carreiras'
    | '/manutencao'
    | '/politica-privacidade'
    | '/servicos'
    | '/sobre'
    | '/estoque/ajustes'
    | '/estoque/entrada'
    | '/estoque/fornecedores'
    | '/estoque/movimentacoes'
    | '/estoque/produtos'
    | '/estoque/saida'
    | '/estoque/sites'
    | '/financeiro/categorias'
    | '/financeiro/clientes'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-bancarias'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/relatorios'
    | '/'
    | '/app'
    | '/engenharia'
    | '/estoque'
    | '/financeiro'
    | '/rh'
    | '/projetos/$id'
    | '/projetos'
  id:
    | '__root__'
    | '/app'
    | '/engenharia'
    | '/estoque'
    | '/financeiro'
    | '/rh'
    | '/_website'
    | '/login'
    | '/_website/carreiras'
    | '/_website/manutencao'
    | '/_website/politica-privacidade'
    | '/_website/servicos'
    | '/_website/sobre'
    | '/estoque/ajustes'
    | '/estoque/entrada'
    | '/estoque/fornecedores'
    | '/estoque/movimentacoes'
    | '/estoque/produtos'
    | '/estoque/saida'
    | '/estoque/sites'
    | '/financeiro/categorias'
    | '/financeiro/clientes'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-bancarias'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/relatorios'
    | '/_website/'
    | '/app/'
    | '/engenharia/'
    | '/estoque/'
    | '/financeiro/'
    | '/rh/'
    | '/_website/projetos/$id'
    | '/_website/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  EngenhariaRouteRoute: typeof EngenhariaRouteRouteWithChildren
  EstoqueRouteRoute: typeof EstoqueRouteRouteWithChildren
  FinanceiroRouteRoute: typeof FinanceiroRouteRouteWithChildren
  RhRouteRoute: typeof RhRouteRouteWithChildren
  WebsiteRoute: typeof WebsiteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_website': {
      id: '/_website'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia': {
      id: '/engenharia'
      path: '/engenharia'
      fullPath: '/engenharia'
      preLoaderRoute: typeof EngenhariaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/': {
      id: '/rh/'
      path: '/'
      fullPath: '/rh/'
      preLoaderRoute: typeof RhIndexRouteImport
      parentRoute: typeof RhRouteRoute
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRouteRoute
    }
    '/estoque/': {
      id: '/estoque/'
      path: '/'
      fullPath: '/estoque/'
      preLoaderRoute: typeof EstoqueIndexRouteImport
      parentRoute: typeof EstoqueRouteRoute
    }
    '/engenharia/': {
      id: '/engenharia/'
      path: '/'
      fullPath: '/engenharia/'
      preLoaderRoute: typeof EngenhariaIndexRouteImport
      parentRoute: typeof EngenhariaRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_website/': {
      id: '/_website/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/financeiro/relatorios': {
      id: '/financeiro/relatorios'
      path: '/relatorios'
      fullPath: '/financeiro/relatorios'
      preLoaderRoute: typeof FinanceiroRelatoriosRouteImport
      parentRoute: typeof FinanceiroRouteRoute
    }
    '/financeiro/contas-receber': {
      id: '/financeiro/contas-receber'
      path: '/contas-receber'
      fullPath: '/financeiro/contas-receber'
      preLoaderRoute: typeof FinanceiroContasReceberRouteImport
      parentRoute: typeof FinanceiroRouteRoute
    }
    '/financeiro/contas-pagar': {
      id: '/financeiro/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/financeiro/contas-pagar'
      preLoaderRoute: typeof FinanceiroContasPagarRouteImport
      parentRoute: typeof FinanceiroRouteRoute
    }
    '/financeiro/contas-bancarias': {
      id: '/financeiro/contas-bancarias'
      path: '/contas-bancarias'
      fullPath: '/financeiro/contas-bancarias'
      preLoaderRoute: typeof FinanceiroContasBancariasRouteImport
      parentRoute: typeof FinanceiroRouteRoute
    }
    '/financeiro/conciliacao': {
      id: '/financeiro/conciliacao'
      path: '/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof FinanceiroConciliacaoRouteImport
      parentRoute: typeof FinanceiroRouteRoute
    }
    '/financeiro/clientes': {
      id: '/financeiro/clientes'
      path: '/clientes'
      fullPath: '/financeiro/clientes'
      preLoaderRoute: typeof FinanceiroClientesRouteImport
      parentRoute: typeof FinanceiroRouteRoute
    }
    '/financeiro/categorias': {
      id: '/financeiro/categorias'
      path: '/categorias'
      fullPath: '/financeiro/categorias'
      preLoaderRoute: typeof FinanceiroCategoriasRouteImport
      parentRoute: typeof FinanceiroRouteRoute
    }
    '/estoque/sites': {
      id: '/estoque/sites'
      path: '/sites'
      fullPath: '/estoque/sites'
      preLoaderRoute: typeof EstoqueSitesRouteImport
      parentRoute: typeof EstoqueRouteRoute
    }
    '/estoque/saida': {
      id: '/estoque/saida'
      path: '/saida'
      fullPath: '/estoque/saida'
      preLoaderRoute: typeof EstoqueSaidaRouteImport
      parentRoute: typeof EstoqueRouteRoute
    }
    '/estoque/produtos': {
      id: '/estoque/produtos'
      path: '/produtos'
      fullPath: '/estoque/produtos'
      preLoaderRoute: typeof EstoqueProdutosRouteImport
      parentRoute: typeof EstoqueRouteRoute
    }
    '/estoque/movimentacoes': {
      id: '/estoque/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof EstoqueMovimentacoesRouteImport
      parentRoute: typeof EstoqueRouteRoute
    }
    '/estoque/fornecedores': {
      id: '/estoque/fornecedores'
      path: '/fornecedores'
      fullPath: '/estoque/fornecedores'
      preLoaderRoute: typeof EstoqueFornecedoresRouteImport
      parentRoute: typeof EstoqueRouteRoute
    }
    '/estoque/entrada': {
      id: '/estoque/entrada'
      path: '/entrada'
      fullPath: '/estoque/entrada'
      preLoaderRoute: typeof EstoqueEntradaRouteImport
      parentRoute: typeof EstoqueRouteRoute
    }
    '/estoque/ajustes': {
      id: '/estoque/ajustes'
      path: '/ajustes'
      fullPath: '/estoque/ajustes'
      preLoaderRoute: typeof EstoqueAjustesRouteImport
      parentRoute: typeof EstoqueRouteRoute
    }
    '/_website/sobre': {
      id: '/_website/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof WebsiteSobreRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_website/servicos': {
      id: '/_website/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof WebsiteServicosRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_website/politica-privacidade': {
      id: '/_website/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof WebsitePoliticaPrivacidadeRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_website/manutencao': {
      id: '/_website/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof WebsiteManutencaoRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_website/carreiras': {
      id: '/_website/carreiras'
      path: '/carreiras'
      fullPath: '/carreiras'
      preLoaderRoute: typeof WebsiteCarreirasRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_website/projetos/': {
      id: '/_website/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof WebsiteProjetosIndexRouteImport
      parentRoute: typeof WebsiteRoute
    }
    '/_website/projetos/$id': {
      id: '/_website/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof WebsiteProjetosIdRouteImport
      parentRoute: typeof WebsiteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface EngenhariaRouteRouteChildren {
  EngenhariaIndexRoute: typeof EngenhariaIndexRoute
}

const EngenhariaRouteRouteChildren: EngenhariaRouteRouteChildren = {
  EngenhariaIndexRoute: EngenhariaIndexRoute,
}

const EngenhariaRouteRouteWithChildren = EngenhariaRouteRoute._addFileChildren(
  EngenhariaRouteRouteChildren,
)

interface EstoqueRouteRouteChildren {
  EstoqueAjustesRoute: typeof EstoqueAjustesRoute
  EstoqueEntradaRoute: typeof EstoqueEntradaRoute
  EstoqueFornecedoresRoute: typeof EstoqueFornecedoresRoute
  EstoqueMovimentacoesRoute: typeof EstoqueMovimentacoesRoute
  EstoqueProdutosRoute: typeof EstoqueProdutosRoute
  EstoqueSaidaRoute: typeof EstoqueSaidaRoute
  EstoqueSitesRoute: typeof EstoqueSitesRoute
  EstoqueIndexRoute: typeof EstoqueIndexRoute
}

const EstoqueRouteRouteChildren: EstoqueRouteRouteChildren = {
  EstoqueAjustesRoute: EstoqueAjustesRoute,
  EstoqueEntradaRoute: EstoqueEntradaRoute,
  EstoqueFornecedoresRoute: EstoqueFornecedoresRoute,
  EstoqueMovimentacoesRoute: EstoqueMovimentacoesRoute,
  EstoqueProdutosRoute: EstoqueProdutosRoute,
  EstoqueSaidaRoute: EstoqueSaidaRoute,
  EstoqueSitesRoute: EstoqueSitesRoute,
  EstoqueIndexRoute: EstoqueIndexRoute,
}

const EstoqueRouteRouteWithChildren = EstoqueRouteRoute._addFileChildren(
  EstoqueRouteRouteChildren,
)

interface FinanceiroRouteRouteChildren {
  FinanceiroCategoriasRoute: typeof FinanceiroCategoriasRoute
  FinanceiroClientesRoute: typeof FinanceiroClientesRoute
  FinanceiroConciliacaoRoute: typeof FinanceiroConciliacaoRoute
  FinanceiroContasBancariasRoute: typeof FinanceiroContasBancariasRoute
  FinanceiroContasPagarRoute: typeof FinanceiroContasPagarRoute
  FinanceiroContasReceberRoute: typeof FinanceiroContasReceberRoute
  FinanceiroRelatoriosRoute: typeof FinanceiroRelatoriosRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
}

const FinanceiroRouteRouteChildren: FinanceiroRouteRouteChildren = {
  FinanceiroCategoriasRoute: FinanceiroCategoriasRoute,
  FinanceiroClientesRoute: FinanceiroClientesRoute,
  FinanceiroConciliacaoRoute: FinanceiroConciliacaoRoute,
  FinanceiroContasBancariasRoute: FinanceiroContasBancariasRoute,
  FinanceiroContasPagarRoute: FinanceiroContasPagarRoute,
  FinanceiroContasReceberRoute: FinanceiroContasReceberRoute,
  FinanceiroRelatoriosRoute: FinanceiroRelatoriosRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
}

const FinanceiroRouteRouteWithChildren = FinanceiroRouteRoute._addFileChildren(
  FinanceiroRouteRouteChildren,
)

interface RhRouteRouteChildren {
  RhIndexRoute: typeof RhIndexRoute
}

const RhRouteRouteChildren: RhRouteRouteChildren = {
  RhIndexRoute: RhIndexRoute,
}

const RhRouteRouteWithChildren =
  RhRouteRoute._addFileChildren(RhRouteRouteChildren)

interface WebsiteRouteChildren {
  WebsiteCarreirasRoute: typeof WebsiteCarreirasRoute
  WebsiteManutencaoRoute: typeof WebsiteManutencaoRoute
  WebsitePoliticaPrivacidadeRoute: typeof WebsitePoliticaPrivacidadeRoute
  WebsiteServicosRoute: typeof WebsiteServicosRoute
  WebsiteSobreRoute: typeof WebsiteSobreRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
  WebsiteProjetosIdRoute: typeof WebsiteProjetosIdRoute
  WebsiteProjetosIndexRoute: typeof WebsiteProjetosIndexRoute
}

const WebsiteRouteChildren: WebsiteRouteChildren = {
  WebsiteCarreirasRoute: WebsiteCarreirasRoute,
  WebsiteManutencaoRoute: WebsiteManutencaoRoute,
  WebsitePoliticaPrivacidadeRoute: WebsitePoliticaPrivacidadeRoute,
  WebsiteServicosRoute: WebsiteServicosRoute,
  WebsiteSobreRoute: WebsiteSobreRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
  WebsiteProjetosIdRoute: WebsiteProjetosIdRoute,
  WebsiteProjetosIndexRoute: WebsiteProjetosIndexRoute,
}

const WebsiteRouteWithChildren =
  WebsiteRoute._addFileChildren(WebsiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  EngenhariaRouteRoute: EngenhariaRouteRouteWithChildren,
  EstoqueRouteRoute: EstoqueRouteRouteWithChildren,
  FinanceiroRouteRoute: FinanceiroRouteRouteWithChildren,
  RhRouteRoute: RhRouteRouteWithChildren,
  WebsiteRoute: WebsiteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
